//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> FontColorId { get; set; }
        public Nullable<int> BackgroundColorId { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Color Color1 { get; set; }
        public virtual User User { get; set; }
    }
}
